import assert from 'node:assert/strict';
import { after, mock, test } from 'node:test';
import { defaultPrBody, parsePrTemplate, PR_TEMPLATE_SCAFFOLD } from '@propr/shared';
import { closeConnection, formatSubscriptionUsage, generateCompletionComment, generateCompletionCommentParts, getDetailedUsageStats, redactSecrets, sanitizeAgentReport } from '@propr/core';
import { describeIssuePullRequestForRepository, generatePRBody, generatePRDescription, type ClaudeResult } from '../src/github/prFormatters.js';
import { buildIssuePullRequestBodyPieces, buildIssueReference, createPullRequest } from '../src/jobs/issueJobHelpers.js';
import { createGitHubPrTemplateSource, describeContinuationPullRequest, loadPullRequestTemplate } from '../src/jobs/pullRequestTemplate.js';
import { buildSlashCommandsBlock } from '../src/shared/slashCommandsBlock.js';

// The template fallback setting is read from the configuration database.
after(() => closeConnection());

/** generatePRBody exactly as it was before templates existed. */
function legacyGeneratePRBody(issueNumber: number, issueTitle: string, commitMessage: string, claudeResult: ClaudeResult | null): string {
    const timestamp = new Date().toISOString();
    const isSuccess = claudeResult?.success || false;
    const executionTime = Math.round((claudeResult?.executionTime || 0) / 1000);
    const { totalInputWithCache: inputTokens, outputTokens, totalTokens } = getDetailedUsageStats(claudeResult as Parameters<typeof getDetailedUsageStats>[0]);
    const cost = claudeResult?.finalResult?.cost_usd || 0;
    let body = `## 🤖 AI-Generated Solution\n\n`;
    body += `Resolves #${issueNumber}.\n\n`;
    body += `This Pull Request was automatically generated by [ProPR](https://propr.dev) to address the issue: **${issueTitle}**\n\n`;
    body += `### 📋 Execution Summary\n\n`;
    body += `- **Status**: ${isSuccess ? '✅ Success' : '❌ Failed'}\n`;
    body += `- **Execution Time**: ${executionTime}s\n`;
    body += `- **Tokens used**: ${totalTokens.toLocaleString()} tokens [${inputTokens.toLocaleString()} input + ${outputTokens.toLocaleString()} output]\n`;
    body += `- **API cost**: $${cost}\n`;
    const subscriptionUsage = formatSubscriptionUsage(claudeResult?.usageMetrics);
    if (subscriptionUsage) body += `- **Subscription usage**: ${subscriptionUsage}\n`;
    body += `- **Generated**: ${timestamp}\n`;
    if (claudeResult?.finalResult) body += `- **Session ID**: \`${claudeResult.sessionId || 'unknown'}\`\n`;
    body += `\n### 💬 Implementation Details\n\n`;
    const publishableCommitMessage = sanitizeAgentReport(commitMessage);
    if (publishableCommitMessage) body += `**Commit Message:**\n\`\`\`\n${publishableCommitMessage}\n\`\`\`\n\n`;
    const publishableSummary = sanitizeAgentReport(claudeResult?.summary);
    if (publishableSummary) body += `**Summary:**\n${publishableSummary}\n\n`;
    body += `**Note:** Detailed conversation logs and execution details will be added as a comment below.\n\n`;
    body += `### ⚙️ Review Guidelines\n\n`;
    body += `- Review the changes carefully before merging\n`;
    body += `- Test the implementation in your development environment\n`;
    body += `- Check that the solution addresses the original issue requirements\n`;
    body += `- Verify that no unintended changes were introduced\n`;
    body += `- **Need changes?** Comment on this PR to request refinements — the AI agent will update the implementation based on your feedback\n\n`;
    body += `---\n`;
    body += buildSlashCommandsBlock();
    body += `\n*This PR was generated automatically by [ProPR](https://propr.dev). Full execution logs are available in the comments.*`;
    return redactSecrets(body);
}

const results: Array<ClaudeResult | null> = [
    null,
    { success: false },
    {
        success: true, executionTime: 125_400, sessionId: 'session-9', summary: 'Fixed the bug.\nI did not create a commit.',
        finalResult: { cost_usd: 0.42, num_turns: 3 }, model: 'claude-opus-4-5-20251101',
        tokenUsage: { input_tokens: 1200, output_tokens: 340, cache_read_input_tokens: 5000 },
    },
];

test('generatePRBody without a template is byte-identical to the historical description', async () => {
    mock.timers.enable({ apis: ['Date'], now: Date.parse('2026-10-06T08:00:00.000Z') });
    try {
        for (const result of results) {
            for (const [title, commit] of [['Fix login', 'fix: login\n\nDetails'], ['<b>Title</b>', '']]) {
                assert.equal(await generatePRBody(7, title, commit, result), legacyGeneratePRBody(7, title, commit, result));
            }
        }
    } finally {
        mock.timers.reset();
    }
});

test('the commented propr init scaffold keeps the historical description', async () => {
    mock.timers.enable({ apis: ['Date'], now: Date.parse('2026-10-06T08:00:00.000Z') });
    try {
        for (const result of results) {
            const octokit = contentsOctokit({ '.propr/pr-template.md': PR_TEMPLATE_SCAFFOLD }, {});
            const described = await describeIssuePullRequestForRepository({
                octokit, owner: 'acme', repoName: 'app', baseBranch: 'main', issueNumber: 7, issueTitle: 'Fix login',
                commitMessage: 'fix: login', claudeResult: result, modelName: 'claude-opus-4-5-20251101',
            });
            assert.equal(described.body, legacyGeneratePRBody(7, 'Fix login', 'fix: login', result));
            assert.match(described.title, /^\[7 by .+\] Fix login$/);
        }
    } finally {
        mock.timers.reset();
    }
});

test('model placeholders use the supplied model when the result has none', async () => {
    const octokit = contentsOctokit({ '.propr/pr-template.md': '## title\n{{model}} via {{agent}}\n' }, {});
    const issue = { octokit, owner: 'acme', repoName: 'app', baseBranch: 'main', issueNumber: 7, issueTitle: 'Fix login', commitMessage: 'fix: login' };
    const described = await describeIssuePullRequestForRepository({ ...issue, claudeResult: { success: true, summary: 'Fixed.' }, modelName: 'claude-opus-4-5-20251101' });
    const expected = await describeIssuePullRequestForRepository({ ...issue, claudeResult: { success: true, summary: 'Fixed.', model: 'claude-opus-4-5-20251101' } });
    assert.equal(described.title, expected.title);
    assert.match(described.title, / via claude$/);
    assert.doesNotMatch(described.title, /^AI via/);
});

test('generatePRDescription applies a template, sanitizing untrusted values', async () => {
    const body = await generatePRDescription({
        issueNumber: 7, issueTitle: '<script>alert(1)</script>', commitMessage: 'fix: login', claudeResult: results[2], repository: 'acme/app',
        template: { kind: 'propr', path: '.propr/pr-template.md', template: parsePrTemplate('## summary\nFixes {{issue_title}} in {{repository}}\n\n{{summary}}\n## run\n\n## commands\n\n## review_guidelines\n- [ ] QA\n') },
    });
    assert.match(body, /^Fixes &lt;script>alert\(1\)&lt;\/script> in acme\/app\n\nFixed the bug\.\n\n### 💬 Implementation Details/);
    assert.doesNotMatch(body, /Execution Summary|did not create a commit|\/review/);
    assert.match(body, /- \[ \] QA\n\n\*This PR was generated automatically/);
});

test('the issue PR description pieces join to the historical description', async () => {
    const issueRef = { number: 42, repoOwner: 'acme', repoName: 'app' };
    const worktreeInfo = { branchName: '42-fix-login' };
    for (const [result, commitResult] of [
        [{ success: true, summary: 'Done.', repositoryValidation: '**Validation:** passed', finalResult: { cost_usd: 0.1 } }, { commitHash: 'abcdef1234567', commitMessage: 'fix' }],
        [{ success: false, terminationReason: 'max_turns', modifiedFiles: ['a.ts'] }, null],
    ] as const) {
        mock.timers.enable({ apis: ['Date'], now: Date.parse('2026-10-06T08:00:00.000Z') });
        try {
            const completionComment = await generateCompletionComment(result, issueRef);
            const legacy = `## AI Implementation Summary

${buildIssueReference(42, commitResult !== null, result as never)}

**Branch:** \`${worktreeInfo.branchName}\`
**Commits:** ${commitResult ? `✅ Changes committed (${commitResult.commitHash.substring(0, 7)})` : '❌ No changes made'}

---

${completionComment}

---

### 💡 Need changes?

Comment on this PR to request refinements — the AI agent monitors comments and will update the implementation based on your feedback. Keep iterating until you're satisfied!`;
            const completion = await generateCompletionCommentParts(result, issueRef);
            const pieces = buildIssuePullRequestBodyPieces({ issueRef, worktreeInfo, commitResult: commitResult as never, claudeResult: result as never, completion });
            assert.equal(defaultPrBody(pieces), legacy);
        } finally {
            mock.timers.reset();
        }
    }
});

function contentsOctokit(files: Record<string, string>, directories: Record<string, Array<{ name: string; path: string; type: string }>>) {
    const calls: Array<{ endpoint: string; options: Record<string, unknown> }> = [];
    return {
        calls,
        async request<T>(endpoint: string, options: Record<string, unknown>): Promise<T> {
            calls.push({ endpoint, options });
            if (endpoint === 'GET /repos/{owner}/{repo}/commits/{ref}') return { data: { sha: 'base-sha' } } as T;
            const path = String(options.path);
            if (path in files) return { data: { name: path.split('/').at(-1), path, type: 'file', encoding: 'base64', content: Buffer.from(files[path]).toString('base64') } } as T;
            if (path in directories) return { data: directories[path] } as T;
            throw Object.assign(new Error('Not Found'), { status: 404 });
        },
    };
}

test('loadPullRequestTemplate reads the template from the base branch head commit', async () => {
    const octokit = contentsOctokit({ '.propr/pr-template.md': '## run\n' }, {});
    const template = await loadPullRequestTemplate({ octokit, repoOwner: 'acme', repoName: 'app', baseBranch: 'develop' });
    assert.deepEqual(template, { kind: 'propr', path: '.propr/pr-template.md', template: { sections: { run: '' }, problems: [] } });
    assert.deepEqual(octokit.calls.map(call => call.options.ref), ['develop', 'base-sha']);
});

test('the GitHub-backed source lists directories and rejects non-file template paths', async () => {
    const octokit = contentsOctokit({ '.github/pull_request_template.md': '- [ ] tested' }, {
        '.github': [{ name: 'pull_request_template.md', path: '.github/pull_request_template.md', type: 'file' }],
    });
    const source = createGitHubPrTemplateSource(octokit, 'acme', 'app');
    assert.deepEqual(await source.listDirectory('.github', 'base-sha'), [{ name: 'pull_request_template.md', path: '.github/pull_request_template.md', type: 'file' }]);
    assert.equal(await source.listDirectory('docs', 'base-sha'), null);
    assert.deepEqual(await source.readFile('.github/pull_request_template.md', 'base-sha'), { content: '- [ ] tested' });
    assert.equal(await source.readFile('missing.md', 'base-sha'), null);
    await assert.rejects(source.readFile('.github', 'base-sha'), /regular UTF-8 file/);
});

test('continuation PRs keep their marker and default text unless a template shapes them', async () => {
    const record = { repository: 'acme/app', source_pr: 42, source_title: 'Contribution', branch_name: 'propr/continuation-pr-42', base_branch: 'main' };
    const marker = '<!-- propr-continuation:42:abc -->';
    const fallback = `${marker}\nContinuation of #42.`;
    const describe = (files: Record<string, string>, maxLength = 65536) => describeContinuationPullRequest({ octokit: contentsOctokit(files, {}), record, marker, fallback, maxLength });

    assert.equal(await describe({}), fallback);
    assert.equal(await describe({ '.propr/pr-template.md': '## summary\nContinues {{issue_title}} on {{branch}}\n## trailer\n- [ ] QA\n' }),
        `${marker}\nContinues Contribution on propr/continuation-pr-42\n\n- [ ] QA`);
    assert.equal(await describe({ '.propr/pr-template.md': '## trailer\n- [ ] QA\n' }), `${fallback}\n\n- [ ] QA`);
    assert.equal(await describe({ '.propr/pr-template.md': '## trailer\n- [ ] QA\n' }, fallback.length), fallback);
    assert.equal(await describe({ '.propr/pr-template.md': '## summary\n{{broken}}\n' }), fallback);
});

test('describeIssuePullRequestForRepository applies the base-branch template to title and body', async () => {
    const issue = { owner: 'acme', repoName: 'app', baseBranch: 'develop', branch: '7-fix', issueNumber: 7, issueTitle: 'Fix login', commitMessage: 'fix: login', claudeResult: results[2], modelName: 'claude-opus-4-5-20251101' };
    const octokit = contentsOctokit({ '.propr/pr-template.md': '## title\nfix: {{issue_title}} (#{{issue_number}})\n## summary\nCloses #{{issue_number}} in {{repository}}\n' }, {});
    const templated = await describeIssuePullRequestForRepository({ octokit, ...issue });
    assert.equal(templated.title, 'fix: Fix login (#7)');
    assert.match(templated.body, /^Closes #7 in acme\/app\n\n### 📋 Execution Summary/);
    assert.deepEqual(octokit.calls.map(call => call.options.ref), ['develop', 'base-sha']);

    const plain = await describeIssuePullRequestForRepository({ octokit: contentsOctokit({}, {}), ...issue, baseBranch: 'main' });
    assert.match(plain.title, /^\[7 by .+\] Fix login$/);
    assert.match(plain.body, /^## 🤖 AI-Generated Solution/);
});

const SECRET_BRANCH = 'fix/ghp_abcdefghijklmnopqrstuvwxyz0123456789';
const SECRET_TITLE_TEMPLATE = { '.propr/pr-template.md': '## title\n{{branch}}: {{issue_title}} {{session_id}}\n' };

test('describeIssuePullRequestForRepository never publishes a secret from a title placeholder', async () => {
    const described = await describeIssuePullRequestForRepository({
        octokit: contentsOctokit(SECRET_TITLE_TEMPLATE, {}), owner: 'acme', repoName: 'app', baseBranch: 'main', branch: SECRET_BRANCH,
        issueNumber: 7, issueTitle: 'Fix login', commitMessage: 'fix: login', claudeResult: { ...results[2], sessionId: 'sk-ant-abcdefghijklmnopqrstuvwxyz0123456789' },
        modelName: 'claude-opus-4-5-20251101',
    });
    assert.equal(described.title, 'fix/[REDACTED_GITHUB_TOKEN]: Fix login [REDACTED_ANTHROPIC_KEY]');
});

test('createPullRequest never publishes a secret from a title placeholder', async () => {
    const octokit = contentsOctokit(SECRET_TITLE_TEMPLATE, {});
    const request = octokit.request.bind(octokit);
    const published: Array<Record<string, unknown>> = [];
    const mockOctokit = {
        async request<T>(endpoint: string, options: Record<string, unknown>): Promise<T> {
            if (endpoint === 'POST /repos/{owner}/{repo}/pulls') {
                published.push(options);
                return { data: { number: 9, html_url: 'https://github.com/acme/app/pull/9', title: options.title } } as T;
            }
            if (endpoint.startsWith('POST /repos/{owner}/{repo}/issues/')) return { data: [] } as T;
            return request<T>(endpoint, options);
        },
    };
    const logger = { info() {}, warn() {}, error() {}, debug() {} };
    await createPullRequest(mockOctokit as never, { repoOwner: 'acme', repoName: 'app', number: 7, baseBranch: 'main' } as never, { branchName: SECRET_BRANCH } as never, {
        commitResult: null, claudeResult: null, modelName: 'claude-opus-4-5-20251101', repoValidation: {} as never, PR_LABEL: 'propr',
        correlatedLogger: logger as never, issueTitle: 'Fix login',
    });
    assert.equal(published.length, 1);
    assert.equal(published[0].title, 'fix/[REDACTED_GITHUB_TOKEN]: Fix login');
});
