// Public persistence exports kept out of the package root barrel so its API
// remains explicit while the root stays within the repository line limit.
export {
  getCategoriesForRepository,
  createCategory,
  updateCategory,
  deleteCategory,
  batchReorderCategories,
  getTodosForRepository,
  getTodo,
  createTodo,
  updateTodo,
  deleteTodo,
  batchReorderTodos,
  linkTodosToDraft,
  completeTodosForDraft,
  getTodosForDraft,
  type RepoTodoCategoryRecord,
  type RepoTodoRecord,
  type RepoTodoCategory,
  type RepoTodo,
  type CreateCategoryParams,
  type UpdateCategoryParams,
  type CreateTodoParams,
  type UpdateTodoParams,
  type BatchReorderItem,
} from '../repoTodosService.js';

export {
  NotificationService,
  NotificationEventNotFoundError,
  NotificationValidationError,
  PushSubscriptionConflictError,
  PushSubscriptionQuotaError,
  PushSubscriptionRateLimitError,
  MAX_ACTIVE_PUSH_SUBSCRIPTIONS_PER_USER,
  MAX_STORED_PUSH_SUBSCRIPTIONS_PER_USER,
  MAX_PUSH_SUBSCRIPTION_ENROLLMENTS_PER_WINDOW,
  PUSH_SUBSCRIPTION_ENROLLMENT_WINDOW_MS,
  PUSH_SUBSCRIPTION_REVOKED_RETENTION_MS,
  PUSH_SUBSCRIPTION_GC_BATCH_SIZE,
  notificationService,
  createNotificationEvent,
  assignNotificationRecipients,
  listNotifications,
  getUnreadNotificationCount,
  markNotificationRead,
  dismissNotification,
  getNotificationPreferences,
  updateNotificationPreferences,
  updateNotificationPreference,
  upsertPushSubscription,
  listPushSubscriptions,
  revokePushSubscription,
  revokePushSubscriptionById,
  garbageCollectPushSubscriptions,
  type NotificationRecipientInput,
  type NotificationRecipient,
  type CreateNotificationEventInput,
  type NotificationListOptions,
  type NotificationServiceOptions,
} from '../notificationService.js';

export {
  DEFAULT_NOTIFICATION_LIST_LIMIT,
  MAX_NOTIFICATION_LIST_LIMIT,
  NotificationQueryValidationError,
  parseNotificationListLimit,
  encodeNotificationCursor,
  decodeNotificationCursor,
  type NotificationCursor,
} from '../notificationPagination.js';
