/**
 * GitHub App helper commands.
 *
 * Generates a ready-to-submit GitHub App manifest and a matching `.env`
 * snippet so self-hosters can run ProPR with their own GitHub App in
 * `GITHUB_EVENT_INTAKE_MODE=direct_webhook` mode without hand-assembling
 * permissions, webhook events, and a webhook secret.
 */

import { Command } from "commander";
import crypto from "crypto";
import path from "path";
import { writeFile } from "fs/promises";
import { existsSync } from "fs";
import { printOutput } from "../utils/io.js";

/** Output filenames written by `propr github-app manifest`. */
export const MANIFEST_FILENAME = "github-app-manifest.json";
export const ENV_FILENAME = "github-app.env";

/**
 * Repository permissions ProPR requires to implement issues, push branches,
 * open pull requests, and read CI status. Kept here as the single source of
 * truth for the generated manifest.
 */
export const PROPR_APP_PERMISSIONS: Record<string, string> = {
  contents: "write",
  issues: "write",
  pull_requests: "write",
  metadata: "read",
  actions: "read",
};

/**
 * Webhook events ProPR's core webhook handler understands. Mirrors
 * SUPPORTED_WEBHOOK_EVENTS in @propr/core (the CLI does not depend on core,
 * so the list is duplicated intentionally and kept in sync).
 */
export const PROPR_WEBHOOK_EVENTS: string[] = [
  "issues",
  "issue_comment",
  "pull_request_review_comment",
  "pull_request",
  "check_run",
  "push",
  "status",
];

export interface GithubAppManifest {
  name: string;
  url: string;
  hook_attributes: {
    url: string;
    active: boolean;
    secret: string;
  };
  redirect_url: string;
  public: boolean;
  default_permissions: Record<string, string>;
  default_events: string[];
}

export interface GenerateManifestOptions {
  /** Output directory for the manifest + env files. Defaults to process.cwd(). */
  root?: string;
  /** Public base URL where GitHub can reach this ProPR install (required). */
  publicUrl: string;
  /** Override the webhook delivery URL. Defaults to `<publicUrl>/webhook`. */
  webhookUrl?: string;
  /** GitHub App name shown in the manifest. Defaults to "ProPR". */
  name?: string;
  /** Webhook secret. A cryptographically strong one is generated when omitted. */
  webhookSecret?: string;
  /** Overwrite existing output files. */
  force?: boolean;
}

export interface GenerateManifestResult {
  directory: string;
  manifestPath: string;
  envPath: string;
  publicUrl: string;
  webhookUrl: string;
  webhookSecret: string;
  manifest: GithubAppManifest;
  /** GitHub URL where the user submits the manifest to create the App. */
  createUrl: string;
}

/** Generate a cryptographically strong webhook secret (64 hex chars). */
export function generateWebhookSecret(): string {
  return crypto.randomBytes(32).toString("hex");
}

/** Strip trailing slashes so URL joins do not produce `//`. */
function normalizeBaseUrl(url: string): string {
  return url.trim().replace(/\/+$/, "");
}

/**
 * Validate and normalize the public base URL. Throws on anything that is not
 * an absolute http(s) URL.
 */
function resolvePublicUrl(publicUrl: string | undefined): string {
  const raw = (publicUrl ?? "").trim();
  if (!raw) {
    throw new Error(
      "A public base URL is required. Pass --public-url https://propr.example.com"
    );
  }

  let parsed: URL;
  try {
    parsed = new URL(raw);
  } catch {
    throw new Error(`Invalid --public-url: "${raw}" is not a valid URL`);
  }

  if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
    throw new Error(
      `Invalid --public-url: "${raw}" must use http:// or https://`
    );
  }

  return normalizeBaseUrl(raw);
}

/** Build the GitHub App manifest object from resolved settings. */
export function buildManifest(params: {
  name: string;
  publicUrl: string;
  webhookUrl: string;
  webhookSecret: string;
}): GithubAppManifest {
  return {
    name: params.name,
    url: params.publicUrl,
    hook_attributes: {
      url: params.webhookUrl,
      active: true,
      secret: params.webhookSecret,
    },
    redirect_url: `${params.publicUrl}/`,
    public: false,
    default_permissions: { ...PROPR_APP_PERMISSIONS },
    default_events: [...PROPR_WEBHOOK_EVENTS],
  };
}

/** Build the `.env` snippet for direct webhook mode. */
export function buildEnvSnippet(params: {
  webhookUrl: string;
  webhookSecret: string;
}): string {
  return `# Generated by \`propr github-app manifest\`.
# Direct webhook intake settings for running ProPR with your own GitHub App.
# Append these to your .env (and fill in GH_APP_ID / GH_INSTALLATION_ID /
# GH_PRIVATE_KEY_PATH after creating and installing the App on GitHub).

GH_AUTH_MODE=app
GITHUB_EVENT_INTAKE_MODE=direct_webhook
GH_WEBHOOK_SECRET=${params.webhookSecret}

# Public webhook endpoint GitHub will deliver events to:
#   ${params.webhookUrl}

# Fill these in from the created GitHub App:
# GH_APP_ID=
# GH_INSTALLATION_ID=
# GH_PRIVATE_KEY_PATH=./github-app-private-key.pem
`;
}

/**
 * Generate the GitHub App manifest JSON and matching `.env` snippet on disk.
 *
 * Safe to run repeatedly: refuses to overwrite existing output files unless
 * `force` is set.
 */
export async function generateGithubAppManifest(
  options: GenerateManifestOptions
): Promise<GenerateManifestResult> {
  const directory = options.root ? path.resolve(options.root) : process.cwd();
  const publicUrl = resolvePublicUrl(options.publicUrl);

  const webhookUrl = options.webhookUrl
    ? options.webhookUrl.trim()
    : `${publicUrl}/webhook`;

  const name = (options.name ?? "ProPR").trim() || "ProPR";
  const webhookSecret =
    options.webhookSecret && options.webhookSecret.trim()
      ? options.webhookSecret.trim()
      : generateWebhookSecret();

  const manifestPath = path.join(directory, MANIFEST_FILENAME);
  const envPath = path.join(directory, ENV_FILENAME);

  if (!options.force) {
    const existing = [manifestPath, envPath].filter((p) => existsSync(p));
    if (existing.length > 0) {
      throw new Error(
        `Refusing to overwrite existing file(s): ${existing
          .map((p) => path.basename(p))
          .join(", ")}. Re-run with --force to overwrite.`
      );
    }
  }

  const manifest = buildManifest({ name, publicUrl, webhookUrl, webhookSecret });
  const envSnippet = buildEnvSnippet({ webhookUrl, webhookSecret });

  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf-8");
  await writeFile(envPath, envSnippet, "utf-8");

  return {
    directory,
    manifestPath,
    envPath,
    publicUrl,
    webhookUrl,
    webhookSecret,
    manifest,
    createUrl: "https://github.com/settings/apps/new",
  };
}

function displayResult(result: GenerateManifestResult): void {
  console.log("Generated GitHub App manifest for direct webhook mode:");
  console.log(`  Manifest: ${result.manifestPath}`);
  console.log(`  Env file: ${result.envPath}`);
  console.log("");
  console.log(`  Webhook URL: ${result.webhookUrl}`);
  console.log(`  Webhook secret: ${result.webhookSecret}`);
  console.log("");
  console.log("Next steps:");
  console.log(
    `  1. Create the App from the manifest at:\n     ${result.createUrl}`
  );
  console.log(
    "     (paste the manifest JSON, or use GitHub's manifest flow with this file)"
  );
  console.log(
    `  2. Append ${path.basename(result.envPath)} to your .env and fill in`
  );
  console.log("     GH_APP_ID, GH_INSTALLATION_ID, and GH_PRIVATE_KEY_PATH.");
}

export function createGithubAppCommand(): Command {
  const command = new Command("github-app");

  command.description(
    "Helpers for running ProPR with your own GitHub App (direct webhook mode)"
  );

  command
    .command("manifest")
    .description(
      "Generate a GitHub App manifest + matching .env snippet for direct webhook mode"
    )
    .requiredOption(
      "--public-url <url>",
      "Public base URL GitHub can reach (e.g. https://propr.example.com)"
    )
    .option(
      "--root <path>",
      "Directory to write output files into (default: current directory)"
    )
    .option(
      "--webhook-url <url>",
      "Override the webhook delivery URL (default: <public-url>/webhook)"
    )
    .option("--name <name>", "GitHub App name in the manifest", "ProPR")
    .option(
      "--webhook-secret <secret>",
      "Webhook secret to use (default: a generated cryptographically strong secret)"
    )
    .option("-f, --force", "Overwrite existing output files")
    .option("-j, --json", "Output result as JSON")
    .addHelpText(
      "after",
      `
Example:
  $ propr github-app manifest --root /srv/propr --public-url https://propr.example.com

Writes ${MANIFEST_FILENAME} and ${ENV_FILENAME} into the target directory.
`
    )
    .action(
      async (options: {
        publicUrl: string;
        root?: string;
        webhookUrl?: string;
        name?: string;
        webhookSecret?: string;
        force?: boolean;
        json?: boolean;
      }) => {
        try {
          const result = await generateGithubAppManifest({
            root: options.root,
            publicUrl: options.publicUrl,
            webhookUrl: options.webhookUrl,
            name: options.name,
            webhookSecret: options.webhookSecret,
            force: options.force,
          });

          if (printOutput(result, !!options.json)) {
            return;
          }
          displayResult(result);
        } catch (error) {
          console.error(
            `Error generating GitHub App manifest: ${(error as Error).message}`
          );
          process.exit(1);
        }
      }
    );

  return command;
}
