import logger from '../utils/logger.js';
import {
    ROUTING_HUB_PROTOCOL_VERSION,
    type MinimalWebSocket,
    WS_OPEN,
} from './routingWebSocketProtocol.js';

const DEFAULT_PING_INTERVAL_MS = 5 * 60 * 1000;
const DEFAULT_PONG_TIMEOUT_MS = 30 * 1000;

function parsePositiveIntegerEnv(name: string): number | undefined {
    const value = process.env[name];
    if (!value) return undefined;
    const trimmed = value.trim();
    // Require a whole-string positive integer so values like `50abc` or `1.5`
    // are rejected rather than silently coerced to `50`/`1`.
    if (!/^\d+$/.test(trimmed)) return undefined;
    const parsed = Number.parseInt(trimmed, 10);
    return Number.isFinite(parsed) && parsed > 0 ? parsed : undefined;
}

export function resolveRoutingPingIntervalMs(optionValue: number | undefined): number {
    return optionValue ?? parsePositiveIntegerEnv('PROPR_ROUTING_WS_PING_INTERVAL_MS') ?? DEFAULT_PING_INTERVAL_MS;
}

export function resolveRoutingPongTimeoutMs(optionValue: number | undefined): number {
    return optionValue ?? parsePositiveIntegerEnv('PROPR_ROUTING_WS_PONG_TIMEOUT_MS') ?? DEFAULT_PONG_TIMEOUT_MS;
}

interface RoutingWebSocketKeepaliveOptions {
    pingIntervalMs: number;
    pongTimeoutMs: number;
    isCurrentSocket: (socket: MinimalWebSocket) => boolean;
    onStaleConnection: () => void;
}

export class RoutingWebSocketKeepalive {
    private readonly pingIntervalMs: number;
    private readonly pongTimeoutMs: number;
    private readonly isCurrentSocket: (socket: MinimalWebSocket) => boolean;
    private readonly onStaleConnection: () => void;

    private pingTimer: NodeJS.Timeout | null = null;
    private heartbeatDeadlineTimer: NodeJS.Timeout | null = null;
    private applicationHeartbeatNegotiated = false;

    constructor(options: RoutingWebSocketKeepaliveOptions) {
        this.pingIntervalMs = options.pingIntervalMs;
        this.pongTimeoutMs = options.pongTimeoutMs;
        this.isCurrentSocket = options.isCurrentSocket;
        this.onStaleConnection = options.onStaleConnection;
    }

    start(socket: MinimalWebSocket): void {
        this.stop();
        this.applicationHeartbeatNegotiated = false;
        this.pingTimer = setInterval(() => {
            if (!this.isCurrentSocket(socket) || socket.readyState !== WS_OPEN) return;

            // Do not let a short custom interval continually postpone the
            // deadline for an unanswered heartbeat. One outstanding probe is
            // enough to establish whether the connection is still usable.
            if (this.heartbeatDeadlineTimer) return;

            this.heartbeatDeadlineTimer = setTimeout(() => {
                this.heartbeatDeadlineTimer = null;
                if (!this.isCurrentSocket(socket) || socket.readyState !== WS_OPEN) return;
                logger.warn(
                    { pongTimeoutMs: this.pongTimeoutMs },
                    'Routing WebSocket application heartbeat deadline expired; terminating stale connection',
                );
                this.onStaleConnection();
                try {
                    // `ws.terminate()` emits `close`, whose existing handler owns
                    // reconnect scheduling and cleanup.
                    socket.terminate();
                } catch (error) {
                    logger.error(
                        { error: (error as Error).message },
                        'Failed to terminate stale routing WebSocket',
                    );
                }
            }, this.pongTimeoutMs);

            try {
                // A transport pong can be generated by an intermediary (for the
                // hosted relay, Cloudflare's edge) even when the RoutingHub
                // application no longer sees this socket. The hello probe is
                // answered by the RoutingHub itself with an application ping.
                socket.send(JSON.stringify({
                    type: 'hello',
                    protocolVersion: ROUTING_HUB_PROTOCOL_VERSION,
                }));
                socket.ping();
            } catch (error) {
                this.clearHeartbeatDeadline();
                logger.warn(
                    { error: (error as Error).message },
                    'Routing WebSocket heartbeat probe failed; terminating connection',
                );
                this.onStaleConnection();
                try {
                    socket.terminate();
                } catch {
                    // The socket is already unusable; its close handler normally
                    // owns reconnect scheduling.
                }
            }
        }, this.pingIntervalMs);
    }

    /**
     * Preserve compatibility with older/self-hosted relays until they answer a
     * hello probe. Once application heartbeat support is observed, transport
     * pongs are deliberately insufficient proof of routing health.
     */
    acknowledgeTransportPong(): void {
        if (!this.applicationHeartbeatNegotiated) this.clearHeartbeatDeadline();
    }

    /** Record proof that a probe reached the RoutingHub application. */
    acknowledgeApplicationHeartbeat(): void {
        this.applicationHeartbeatNegotiated = true;
        this.clearHeartbeatDeadline();
    }

    private clearHeartbeatDeadline(): void {
        if (this.heartbeatDeadlineTimer) {
            clearTimeout(this.heartbeatDeadlineTimer);
            this.heartbeatDeadlineTimer = null;
        }
    }

    stop(): void {
        if (this.pingTimer) {
            clearInterval(this.pingTimer);
            this.pingTimer = null;
        }
        this.clearHeartbeatDeadline();
        this.applicationHeartbeatNegotiated = false;
    }
}
