import { getDetailedUsageStats, getModelPricing, getOpenRouterId, calculateCostWithCachePricing } from '@gitfix/core';
import type { DetailedUsageStats } from '@gitfix/core';

const MAX_COMMENT_LENGTH = 65000;

interface ContentBlock {
    text?: string;
}

interface ConversationLogEntry {
    type: string;
    message?: {
        content?: string | ContentBlock[];
        usage?: {
            input_tokens?: number;
            cache_creation_input_tokens?: number;
            cache_read_input_tokens?: number;
            output_tokens?: number;
        };
    };
}

export interface ClaudeResult {
    success?: boolean;
    executionTime?: number;
    finalResult?: {
        num_turns?: number;
        cost_usd?: number;
        subtype?: string | null;
    };
    sessionId?: string;
    summary?: string;
    conversationLog?: ConversationLogEntry[];
    modifiedFiles?: string[];
    rawOutput?: string;
    exitCode?: number | string;
    model?: string;
    // Cumulative token usage from result message (authoritative per Claude docs)
    tokenUsage?: {
        input_tokens?: number;
        output_tokens?: number;
        cache_creation_input_tokens?: number;
        cache_read_input_tokens?: number;
    };
}

async function calculateApiCost(
    claudeResult: ClaudeResult | null,
    detailedStats: DetailedUsageStats
): Promise<number> {
    const baseCost = claudeResult?.finalResult?.cost_usd || 0;
    if (baseCost !== 0 || detailedStats.totalTokens === 0 || !claudeResult?.model) {
        return baseCost;
    }

    try {
        const openRouterId = getOpenRouterId(claudeResult.model);
        const pricing = await getModelPricing(openRouterId);
        if (pricing) {
            return calculateCostWithCachePricing(claudeResult.model, detailedStats, pricing);
        }
    } catch {
        // Fall back to baseCost if pricing lookup fails
    }
    return baseCost;
}

export async function generatePRBody(issueNumber: number, issueTitle: string, commitMessage: string, claudeResult: ClaudeResult | null): Promise<string> {
    const timestamp = new Date().toISOString();
    const isSuccess = claudeResult?.success || false;
    const executionTime = Math.round((claudeResult?.executionTime || 0) / 1000);
    const detailedStats = getDetailedUsageStats(claudeResult as {
        tokenUsage?: { input_tokens?: number; output_tokens?: number; cache_creation_input_tokens?: number; cache_read_input_tokens?: number };
        conversationLog?: Array<{ message?: { id?: string; usage?: { input_tokens?: number; cache_creation_input_tokens?: number; cache_read_input_tokens?: number; output_tokens?: number } } }>
    } | null);
    const { totalInputWithCache: inputTokens, outputTokens, totalTokens } = detailedStats;

    const cost = await calculateApiCost(claudeResult, detailedStats);

    let body = `## 🤖 AI-Generated Solution\n\n`;
    body += `Resolves #${issueNumber}.\n\n`;
    body += `This Pull Request was automatically generated by [ProPR](https://propr.dev) to address the issue: **${issueTitle}**\n\n`;

    body += `### 📋 Execution Summary\n\n`;
    body += `- **Status**: ${isSuccess ? '✅ Success' : '❌ Failed'}\n`;
    body += `- **Execution Time**: ${executionTime}s\n`;
    body += `- **Tokens used**: ${totalTokens.toLocaleString()} tokens [${inputTokens.toLocaleString()} input + ${outputTokens.toLocaleString()} output]\n`;
    body += `- **API cost**: $${cost}\n`;
    body += `- **Generated**: ${timestamp}\n`;

    if (claudeResult?.finalResult) {
        body += `- **Session ID**: \`${claudeResult.sessionId || 'unknown'}\`\n`;
    }

    body += `\n### 💬 Implementation Details\n\n`;
    if (commitMessage) {
        body += `**Commit Message:**\n\`\`\`\n${commitMessage}\n\`\`\`\n\n`;
    }

    if (claudeResult?.summary) {
        body += `**Summary:**\n${claudeResult.summary}\n\n`;
    }

    body += `**Note:** Detailed conversation logs and execution details will be added as a comment below.\n\n`;
    body += `### ⚙️ Review Guidelines\n\n`;
    body += `- Review the changes carefully before merging\n`;
    body += `- Test the implementation in your development environment\n`;
    body += `- Check that the solution addresses the original issue requirements\n`;
    body += `- Verify that no unintended changes were introduced\n`;
    body += `- **Need changes?** Comment on this PR to request refinements — the AI agent will update the implementation based on your feedback\n\n`;
    body += `---\n*This PR was generated automatically by [ProPR](https://propr.dev). Full execution logs are available in the comments.*`;

    return body;
}

export async function generateClaudeLogsComment(claudeResult: ClaudeResult | null, issueNumber: number): Promise<string> {
    let comment = `## 🔍 ProPR Execution Logs\n\n`;
    comment += `**Issue**: #${issueNumber}\n`;
    comment += `**Session ID**: \`${claudeResult?.sessionId || 'unknown'}\`\n`;
    comment += `**Timestamp**: ${new Date().toISOString()}\n\n`;

    if (claudeResult?.finalResult) {
        const result = claudeResult.finalResult;
        const detailedStats = getDetailedUsageStats(claudeResult as {
        tokenUsage?: { input_tokens?: number; output_tokens?: number; cache_creation_input_tokens?: number; cache_read_input_tokens?: number };
        conversationLog?: Array<{ message?: { id?: string; usage?: { input_tokens?: number; cache_creation_input_tokens?: number; cache_read_input_tokens?: number; output_tokens?: number } } }>
    } | null);
        const { totalInputWithCache: inputTokens, outputTokens, totalTokens } = detailedStats;

        // Calculate cost using OpenRouter pricing with cache-aware multipliers
        const cost = await calculateApiCost(claudeResult, detailedStats);

        comment += `### 📊 Execution Statistics\n\n`;
        comment += `- **Success**: ${claudeResult.success ? 'Yes' : 'No'}\n`;
        comment += `- **Tokens used**: ${totalTokens.toLocaleString()} tokens [${inputTokens.toLocaleString()} input + ${outputTokens.toLocaleString()} output]\n`;
        comment += `- **API cost**: $${cost.toFixed(2)}\n`;
        comment += `- **Execution Time**: ${Math.round((claudeResult.executionTime || 0) / 1000)}s\n`;
        comment += `- **Exit Code**: ${claudeResult.exitCode || 'unknown'}\n\n`;

        if (result.subtype === 'error_max_turns') {
            comment += `⚠️ **Note**: Maximum turns reached (${result.num_turns}). Consider breaking down complex tasks.\n\n`;
        }
    }

    if (claudeResult?.conversationLog && claudeResult.conversationLog.length > 0) {
        comment += `### 💬 Conversation Summary\n\n`;
        comment += `Total messages exchanged: ${claudeResult.conversationLog.length}\n\n`;

        const recentMessages = claudeResult.conversationLog.slice(-5);
        comment += `<details>\n<summary>🗨️ Recent Conversation (Last 5 messages)</summary>\n\n`;

        let conversationSnippet = '';
        recentMessages.forEach((msg) => {
            if (msg.type === 'user') {
                const content = (msg.message?.content as string) || '[content unavailable]';
                conversationSnippet += `**User**: ${content.substring(0, 300)}${content.length > 300 ? '...' : ''}\n\n`;
            } else if (msg.type === 'assistant') {
                const contentArr = msg.message?.content as ContentBlock[] | undefined;
                const content = contentArr?.[0]?.text || '[content unavailable]';
                conversationSnippet += `**Claude**: ${content.substring(0, 300)}${content.length > 300 ? '...' : ''}\n\n`;
            }
        });

        if (comment.length + conversationSnippet.length > MAX_COMMENT_LENGTH - 1000) {
            conversationSnippet = conversationSnippet.substring(0, MAX_COMMENT_LENGTH - comment.length - 1000);
            conversationSnippet += '\n\n[Truncated due to length limits]\n';
        }

        comment += conversationSnippet;
        comment += `\n</details>\n\n`;
    }

    if (claudeResult?.modifiedFiles && claudeResult.modifiedFiles.length > 0) {
        comment += `### 📝 Modified Files\n\n`;
        claudeResult.modifiedFiles.forEach(file => {
            comment += `- \`${file}\`\n`;
        });
        comment += '\n';
    }

    if (comment.length > MAX_COMMENT_LENGTH) {
        const truncatePoint = MAX_COMMENT_LENGTH - 200;
        comment = comment.substring(0, truncatePoint);
        comment += '\n\n[Comment truncated due to GitHub length limits]\n';
        comment += `\nFull logs are available in the system logs.`;
    }

    comment += `---\n*Generated by [ProPR](https://propr.dev)*`;

    return comment;
}
