/**
 * Plan validation shared by generation, repair and refinement.
 *
 * The rules live once, in PLAN_VALIDATOR_SCRIPT: a dependency-free Node script
 * that agents run inside their workspace while they write or repair a plan,
 * and that ProPR runs again on the result, on fresh copies of the script and
 * the original, so an agent cannot pass by editing either.
 */

import { execFile } from 'node:child_process';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

export const PLAN_FILE = 'plan.json';
export const PLAN_ORIGINAL_FILE = 'original.txt';
export const PLAN_VALIDATOR_FILE = 'validate-plan.mjs';
/** Incremental contract: one task object per file, assembled in file-name order. */
export const PLAN_TASKS_DIR = 'tasks';

/**
 * Positions (1-based) of plan items that are not complete issues: a model
 * sometimes returns edit instructions ("retain issue 3") or partial issues.
 */
export function incompletePlanItems(plan: unknown[]): number[] {
  const incomplete: number[] = [];
  plan.forEach((item, index) => {
    const record = item && typeof item === 'object' ? item as Record<string, unknown> : null;
    const complete = !!record && (['title', 'body', 'implementation'] as const)
      .every(field => typeof record[field] === 'string' && (record[field] as string).trim().length > 0);
    if (!complete) incomplete.push(index + 1);
  });
  return incomplete;
}

/**
 * The JSON array in a model response, without surrounding code fences or
 * prose, or null when the response does not hold a whole array. A response
 * that starts or ends mid-array is a fragment: repairing it would silently
 * drop the missing tasks, so it must fail instead.
 */
export function extractWholeJsonArray(response: string): string | null {
  const text = response.trim();
  const start = text.indexOf('[');
  if (start === -1 || /[{}"\]]/.test(text.slice(0, start))) return null;
  if (!/^\[\s*(?:\{|\])/.test(text.slice(start))) return null;

  const end = findJsonArrayEnd(text, start);
  if (end === null) return null;
  // Prose and a closing fence are harmless; JSON-looking suffixes are
  // ambiguous and must not be discarded when establishing the original.
  if (/[[\]{}"]/.test(text.slice(end + 1))) return null;
  return text.slice(start, end + 1);
}

/**
 * Only a balanced outer delimiter outside a string establishes a whole plan.
 * Scan the full response, including fences: stripping a fence first could
 * hide evidence of a trailing task or a fence embedded in task text.
 */
function findJsonArrayEnd(text: string, start: number): number | null {
  const closers: string[] = [];
  let inString = false;
  let escaped = false;
  let previous = '';
  // Match the standalone validator's tolerant string-value boundaries. Sticky
  // lookahead avoids copying the remaining (potentially very large) plan.
  const objectBoundary = /\s*(?:,\s*)?(?:}|"(?:\\.|[^"\\])*"\s*:)/y;
  const arrayBoundary = /\s*(?:,\s*)?(?:\]|"|\{|\[|-?\d|true\b|false\b|null\b)/y;
  let valueBoundary: RegExp | null = null;
  for (let i = start; i < text.length; i++) {
    const char = text[i];
    if (inString) {
      if (escaped) escaped = false;
      else if (char === '\\') escaped = true;
      else if (char === '"') {
        if (valueBoundary) valueBoundary.lastIndex = i + 1;
        if (!valueBoundary || valueBoundary.test(text)) {
          inString = false;
          previous = char;
        }
      }
      continue;
    }
    if (char === '"') {
      inString = true;
      valueBoundary = closers.at(-1) === ']' ? arrayBoundary
        : previous === ':' ? objectBoundary : null;
    } else if (char === '[') closers.push(']');
    else if (char === '{') closers.push('}');
    else if (char === ']' || char === '}') {
      if (closers.pop() !== char) return null;
      if (closers.length === 0) return i;
    }
    if (!/\s/.test(char)) previous = char;
  }
  return null;
}

/**
 * Standalone validator. `node validate-plan.mjs [plan.json] [original.txt]`
 * prints a JSON report and exits 0 only when the plan is valid. With
 * `--tasks <dir>` it first assembles `<dir>/*.json`, one task object per file
 * in file-name order, into plan.json, so a plan too large for one message can
 * be written task by task. With an
 * original present it also proves that the plan keeps the original's content:
 * every task and field matches its original occurrence, in task order. An
 * ambiguous original fails closed rather than authorizing content loss.
 */
export const PLAN_VALIDATOR_SCRIPT = String.raw`#!/usr/bin/env node
// Validates a ProPR plan. Do not edit this file: ProPR re-runs its own copy.
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';

const args = process.argv.slice(2);
const tasksFlag = args.indexOf('--tasks');
const tasksDir = tasksFlag === -1 ? null : (args.splice(tasksFlag, 2)[1] || 'tasks');
const planPath = args[0] || 'plan.json';
const originalPath = args[1] || 'original.txt';
const REQUIRED = ['title', 'body', 'implementation'];
const errors = [];
let taskFiles = [];
let plan;

if (tasksDir !== null) {
  taskFiles = existsSync(tasksDir) ? readdirSync(tasksDir).filter(name => name.endsWith('.json')).sort() : [];
  if (taskFiles.length === 0) errors.push('no task files: write one task object per file as ' + tasksDir + '/001.json, ' + tasksDir + '/002.json, ...');
  const tasks = [];
  for (const name of taskFiles) {
    try {
      const task = JSON.parse(readFileSync(tasksDir + '/' + name, 'utf8'));
      if (Array.isArray(task)) errors.push(tasksDir + '/' + name + ' must hold one task object, not an array');
      else tasks.push(task);
    } catch (error) {
      errors.push(tasksDir + '/' + name + ' is not valid JSON: ' + error.message);
    }
  }
  if (errors.length === 0) writeFileSync(planPath, JSON.stringify(tasks, null, 2) + '\n');
}
const label = index => 'task ' + (index + 1) + (taskFiles[index] ? ' (' + tasksDir + '/' + taskFiles[index] + ')' : '');

if (errors.length === 0) {
  try {
    plan = JSON.parse(readFileSync(planPath, 'utf8'));
  } catch (error) {
    errors.push(planPath + ' is not valid JSON: ' + error.message);
  }
}

if (plan !== undefined) {
  if (!Array.isArray(plan)) errors.push(planPath + ' must contain a JSON array of tasks');
  else if (plan.length === 0) errors.push('the plan has no tasks');
  else plan.forEach((task, index) => {
    if (!task || typeof task !== 'object' || Array.isArray(task)) {
      errors.push(label(index) + ' is not an object');
      return;
    }
    for (const field of REQUIRED) {
      if (typeof task[field] !== 'string' || !task[field].trim()) {
        errors.push(label(index) + ' has no non-empty "' + field + '" string');
      }
    }
  });
}

if (errors.length === 0 && existsSync(originalPath)) {
  // Read the original with only the syntax tolerances needed for repair:
  // missing/trailing commas, raw control characters and unescaped quotes in
  // string values. Keep the tree so occurrences, order and field associations
  // cannot be traded against a global substring or character-count allowance.
  const original = readFileSync(originalPath, 'utf8');
  let offset = 0;
  const whitespace = () => { while (offset < original.length && /\s/.test(original[offset])) offset++; };
  const fail = () => { throw new Error('cannot establish original content at character ' + offset); };
  // One pass consumes escaped backslashes before considering Unicode escapes.
  const decode = text => text.replace(/\\(?:u([0-9a-fA-F]{4})|(["\\/bfnrt]))/g,
    (_, hex, c) => hex !== undefined ? String.fromCharCode(parseInt(hex, 16))
      : ({ b: '\b', f: '\f', n: '\n', r: '\r', t: '\t' })[c] ?? c);
  const string = context => {
    if (original[offset++] !== '"') fail();
    let raw = '';
    while (offset < original.length) {
      const char = original[offset++];
      if (char === '\\') {
        if (offset === original.length) fail();
        raw += char + original[offset++];
      } else if (char === '"') {
        if (context === 'key') return decode(raw);
        const rest = original.slice(offset).trimStart().replace(/^,\s*/, '');
        const atBoundary = context === 'object'
          ? /^(?:}|"(?:\\.|[^"\\])*"\s*:)/.test(rest)
          : /^(?:\]|"|\{|\[|-?\d|true\b|false\b|null\b)/.test(rest);
        if (atBoundary) return decode(raw);
        raw += char;
      } else raw += char;
    }
    fail();
  };
  const value = context => {
    whitespace();
    const char = original[offset];
    if (char === '"') return string(context);
    if (char === '{' || char === '[') {
      offset++;
      const object = char === '{';
      const end = object ? '}' : ']';
      const result = object ? Object.create(null) : [];
      whitespace();
      while (original[offset] !== end) {
        if (offset >= original.length) fail();
        if (object) {
          const key = string('key');
          whitespace();
          if (original[offset++] !== ':' || Object.hasOwn(result, key)) fail();
          result[key] = value('object');
        } else result.push(value('array'));
        whitespace();
        if (original[offset] === ',') { offset++; whitespace(); }
      }
      offset++;
      return result;
    }
    const literal = /^(?:true|false|null|-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?)/.exec(original.slice(offset));
    if (!literal) fail();
    offset += literal[0].length;
    return JSON.parse(literal[0]);
  };
  const same = (before, after) => {
    if (before === null || typeof before !== 'object') return before === after;
    if (after === null || typeof after !== 'object' || Array.isArray(before) !== Array.isArray(after)) return false;
    const keys = Object.keys(before);
    return keys.length === Object.keys(after).length && keys.every(key => Object.hasOwn(after, key) && same(before[key], after[key]));
  };
  try {
    const source = value('array');
    whitespace();
    if (offset !== original.length || !Array.isArray(source)) fail();
    if (source.length !== plan.length) {
      errors.push(originalPath + ' has ' + source.length + ' tasks but ' + planPath + ' has ' + plan.length + ': keep every task');
    }
    source.forEach((task, index) => {
      if (!same(task, plan[index])) {
        errors.push(label(index) + ' does not match ' + originalPath + ': fix syntax only, keep every task and field in its original task');
      }
    });
  } catch (error) {
    errors.push(originalPath + ': ' + error.message + '; cannot verify a syntax-only repair');
  }
}

const report = { valid: errors.length === 0, taskCount: Array.isArray(plan) ? plan.length : 0, errors };
console.log(JSON.stringify(report, null, 2));
process.exit(report.valid ? 0 : 1);
`;

export interface PlanValidationReport {
  valid: boolean;
  taskCount: number;
  errors: string[];
}

async function runOwnValidator(directory: string, args: string[]): Promise<PlanValidationReport> {
  await writeFile(path.join(directory, PLAN_VALIDATOR_FILE), PLAN_VALIDATOR_SCRIPT);
  const { stdout } = await execFileAsync(process.execPath, [PLAN_VALIDATOR_FILE, ...args], {
    cwd: directory, timeout: 30_000, maxBuffer: 1024 * 1024,
  }).catch((error: { stdout?: string; message: string }) => {
    if (typeof error.stdout === 'string' && error.stdout.trim()) return { stdout: error.stdout };
    throw error;
  });
  return JSON.parse(stdout) as PlanValidationReport;
}

/**
 * Validates plan text with ProPR's own copy of the validator, in a private
 * directory, so a workspace's (possibly edited) validator is never trusted.
 */
export async function validatePlanText(planText: string, original?: string): Promise<PlanValidationReport> {
  const directory = await mkdtemp(path.join(tmpdir(), 'propr-plan-validate-'));
  try {
    await writeFile(path.join(directory, PLAN_FILE), planText);
    if (original !== undefined) await writeFile(path.join(directory, PLAN_ORIGINAL_FILE), original);
    return await runOwnValidator(directory, [PLAN_FILE, PLAN_ORIGINAL_FILE]);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}

/**
 * Assembles and validates task files (name → content, one task object each)
 * with ProPR's own validator. Returns the assembled plan text when valid.
 */
export async function validatePlanTaskFiles(taskFiles: Record<string, string>): Promise<PlanValidationReport & { planText: string | null }> {
  const directory = await mkdtemp(path.join(tmpdir(), 'propr-plan-validate-'));
  try {
    await mkdir(path.join(directory, PLAN_TASKS_DIR));
    for (const [name, content] of Object.entries(taskFiles)) {
      if (path.basename(name) !== name || !name.endsWith('.json')) throw new Error(`Invalid task file name: ${name}`);
      await writeFile(path.join(directory, PLAN_TASKS_DIR, name), content);
    }
    const report = await runOwnValidator(directory, ['--tasks', PLAN_TASKS_DIR, PLAN_FILE]);
    const planText = report.valid ? await readFile(path.join(directory, PLAN_FILE), 'utf8') : null;
    return { ...report, planText };
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}
