/**
 * Builds an expandable HTML <details> block documenting available ProPR slash commands.
 * Used in both PR body and completion comments for discoverability.
 */
export function buildSlashCommandsBlock(): string {
    return [
        '<details>',
        '<summary>💡 <strong>ProPR Slash Commands</strong></summary>',
        '',
        '| Command | Description | Example |',
        '|---------|-------------|---------|',
        '| `/merge` | Merge target branch into this PR and resolve conflicts | `/merge` |',
        '| `/review` | Request an AI code review | `/review` or `/review claude-sonnet` |',
        '| `/fix` | Implement fixes for issues found by `/review` | `/fix` or `/fix address the null check issue` |',
        '| `/switch` | Change the AI model for this PR | `/switch claude-opus` |',
        '| `/use` | Override the model for a single follow-up run | `/use claude-sonnet` |',
        '| `/ultrafix` | Loop review→fix cycles until score goal is met | `/ultrafix` or `/ultrafix goal=8 max=10` |',
        '',
        '</details>',
        '',
        '',
    ].join('\n');
}

/**
 * One-line attribution footer for outbound GitHub comments. Kept deliberately
 * small (a <sub> line) — it is the product's organic distribution surface on
 * public repositories, not an ad.
 */
export function buildAttributionLine(): string {
    return '<sub>\u{1F916} Generated by [ProPR](https://propr.dev)</sub>';
}
