export const INDEXING_WORKER_HEARTBEAT_KEY = 'system:status:indexing-worker';
export const INDEXING_WORKER_HEARTBEAT_INTERVAL_MS = 30_000;
export const INDEXING_WORKER_HEARTBEAT_TTL_SECONDS = 90;
export const INDEXING_WORKER_HEARTBEAT_STALE_MS = 120_000;
