#!/usr/bin/env tsx
/**
 * Generates the dashboard API reference from the route registry:
 *
 *   docs/static/openapi/propr-api.yaml        OpenAPI 3.1 spec
 *   packages/client/src/generated/apiTypes.ts  @propr/client request/response types
 *
 * `npm run gen:openapi` writes both files. `npm run gen:openapi:check` writes
 * nothing; it fails when either committed file is stale or the spec does not
 * validate against the OpenAPI 3.1 schema.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import YAML from 'yaml';
import { Validator } from '@seriousme/openapi-schema-validator';
import { buildOpenApiDocument } from '../packages/api/openapi/buildSpec.js';
import { renderClientTypes } from '../packages/api/openapi/clientTypes.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const SPEC_PATH = 'docs/static/openapi/propr-api.yaml';
export const CLIENT_TYPES_PATH = 'packages/client/src/generated/apiTypes.ts';

const SPEC_HEADER = `# Generated by \`npm run gen:openapi\` from packages/api/routeRegistry.ts and
# packages/api/openapi. Do not edit; \`npm run gen:openapi:check\` fails when stale.
`;

export function renderSpecYaml(document: object): string {
  return SPEC_HEADER + YAML.stringify(document, { lineWidth: 0, aliasDuplicateObjects: false });
}

export async function validateSpec(document: object): Promise<string[]> {
  const result = await new Validator().validate(structuredClone(document) as Record<string, unknown>);
  return result.valid ? [] : (Array.isArray(result.errors) ? result.errors : [result.errors])
    .map(error => JSON.stringify(error));
}

async function readOptional(file: string): Promise<string | null> {
  try { return await readFile(path.join(root, file), 'utf8'); } catch { return null; }
}

async function main(): Promise<number> {
  const check = process.argv.includes('--check');
  const document = buildOpenApiDocument();
  const errors = await validateSpec(document);
  if (errors.length) {
    console.error('The generated spec is not a valid OpenAPI 3.1 document:');
    for (const error of errors) console.error(`  ${error}`);
    return 1;
  }
  const outputs: [string, string][] = [
    [SPEC_PATH, renderSpecYaml(document)],
    [CLIENT_TYPES_PATH, renderClientTypes(document)],
  ];
  const coverage = document.info['x-route-coverage'] as { total: number; documented: number; undocumented: number };
  const summary = `${coverage.total} routes, ${coverage.documented} documented, ${coverage.undocumented} x-undocumented`;

  if (check) {
    const stale: string[] = [];
    for (const [file, contents] of outputs) {
      if (await readOptional(file) !== contents) stale.push(file);
    }
    if (stale.length) {
      console.error(`Stale generated API reference: ${stale.join(', ')}`);
      console.error('Run `npm run gen:openapi` and commit the result.');
      return 1;
    }
    console.log(`OpenAPI spec and client types are up to date and valid (${summary}).`);
    return 0;
  }

  for (const [file, contents] of outputs) {
    await mkdir(path.dirname(path.join(root, file)), { recursive: true });
    await writeFile(path.join(root, file), contents);
    console.log(`Wrote ${file}`);
  }
  console.log(`OpenAPI 3.1 spec is valid (${summary}).`);
  return 0;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().then(
    // Route modules open lazy database handles on import; exit explicitly.
    code => process.exit(code),
    error => { console.error(error); process.exit(1); },
  );
}
