#!/usr/bin/env bash
# Regenerate THIRD_PARTY_LICENSES.md with the full license text for every
# production dependency. Run before a release so the notice stays current.
#
# Usage: scripts/generate-notices.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUT="THIRD_PARTY_LICENSES.md"
DATE="$(date +%Y-%m-%d)"

echo "Generating $OUT (this takes ~30s) …"

# --- Header -----------------------------------------------------------------
cat > "$OUT" <<EOF
Third-Party Licenses
====================

This file lists every third-party package bundled in the Propr Docker images,
its license, and (where required) the full license text.

Generated: $DATE
See NOTICE for a higher-level summary and end-user obligations.

---

EOF

# --- AI CLIs (proprietary / Apache) — full text ----------------------------
for entry in \
  "@anthropic-ai/claude-code|node_modules/@anthropic-ai/claude-code/LICENSE.md" \
  "@anthropic-ai/sdk|node_modules/@anthropic-ai/sdk/LICENSE" \
; do
  pkg="${entry%%|*}"
  path="${entry##*|}"
  if [ -f "$path" ]; then
    ver=$(node -p "require('./${path%/LICENSE*}/package.json').version" 2>/dev/null || echo 'unknown')
    {
      echo "## $pkg@$ver"
      echo ""
      echo '```'
      cat "$path"
      echo '```'
      echo ""
    } >> "$OUT"
  fi
done

# @openai/codex, Antigravity CLI, opencode-ai, and mistral-vibe are installed
# only in agent images (not in root node_modules). Reference their licenses.
cat >> "$OUT" <<'EOF'
## @openai/codex (installed in propr/agent-codex image)

Licensed under the Apache License, Version 2.0.
Source: https://github.com/openai/codex

## Antigravity CLI (installed in propr/agent-antigravity image)

Licensed under Google Terms of Service for Google Products and Antigravity
supplemental terms.
Source: https://codeassist.google/

## opencode-ai (installed in propr/agent-opencode image)

Licensed under the MIT License (verified from the published npm package metadata).
Source: https://github.com/sst/opencode


## mistral-vibe (installed in propr/agent-vibe image)

Licensed under the Apache License, Version 2.0.
Source: https://github.com/mistralai/mistral-vibe

---

## Apache License 2.0 (full text)

```
EOF
curl -fsSL https://www.apache.org/licenses/LICENSE-2.0.txt >> "$OUT"
cat >> "$OUT" <<'EOF'
```

---

EOF

# --- All npm production deps via license-checker ----------------------------
{
  echo "## All Propr npm production dependencies"
  echo ""
  echo "Generated by \`license-checker --production\`. Each package listed"
  echo "below is bundled in the propr/app image under the stated license."
  echo ""
  echo '```'
  npx --yes license-checker --production --summary 2>/dev/null || echo "(license-checker failed; install it with: npm i -D license-checker)"
  echo '```'
  echo ""
  echo "### Full per-package list"
  echo ""
  echo '```'
  npx --yes license-checker --production --csv --out /dev/stdout 2>/dev/null \
    | head -500 || echo "(full list generation failed)"
  echo '```'
} >> "$OUT"

wc -l "$OUT" | awk '{print "✓ wrote " $2 " (" $1 " lines)"}'
