import type { OpenApiDocument } from './buildSpec.js';

type JsonSchema = Record<string, unknown>;

const HEADER = `/*
 * Generated by \`npm run gen:openapi\` from packages/api/openapi. Do not edit.
 *
 * Request and response types of the ProPR dashboard API, taken from the same
 * schemas as docs/static/openapi/propr-api.yaml. \`npm run gen:openapi:check\`
 * fails when this file is stale.
 */
/* eslint-disable */
`;

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function jsDoc(description: unknown, indent: string): string {
  if (typeof description !== 'string' || !description) return '';
  const lines = description.split('\n');
  if (lines.length === 1) return `${indent}/** ${description.replace(/\*\//g, '*\\/')} */\n`;
  return `${indent}/**\n${lines.map(line => `${indent} *${line ? ` ${line.replace(/\*\//g, '*\\/')}` : ''}`).join('\n')}\n${indent} */\n`;
}

function union(parts: string[]): string {
  return [...new Set(parts)].join(' | ');
}

function arrayOf(item: string): string {
  return /[|&]/.test(item) ? `Array<${item}>` : `${item}[]`;
}

function objectBody(schema: JsonSchema, indent: string): string {
  const properties = (schema.properties ?? {}) as Record<string, JsonSchema>;
  const required = new Set((schema.required ?? []) as string[]);
  const inner = `${indent}  `;
  const lines = Object.entries(properties).map(([name, property]) => {
    const key = IDENTIFIER.test(name) ? name : JSON.stringify(name);
    return `${jsDoc(property.description, inner)}${inner}${key}${required.has(name) ? '' : '?'}: ${renderType(property, inner)};\n`;
  });
  const additional = schema.additionalProperties;
  if (additional !== undefined && additional !== false) {
    const valueType = additional === true || Object.keys(additional as JsonSchema).length === 0
      ? 'unknown' : renderType(additional as JsonSchema, inner);
    lines.push(`${inner}[key: string]: ${Object.keys(properties).length && valueType !== 'unknown' ? 'unknown' : valueType};\n`);
  }
  return lines.length ? `{\n${lines.join('')}${indent}}` : 'Record<string, never>';
}

export function renderType(schema: JsonSchema, indent = ''): string {
  if (typeof schema.$ref === 'string') return schema.$ref.split('/').pop()!;
  if ('const' in schema) return JSON.stringify(schema.const);
  if (Array.isArray(schema.enum)) return union(schema.enum.map(value => JSON.stringify(value)));
  const variants = (schema.anyOf ?? schema.oneOf) as JsonSchema[] | undefined;
  if (variants) return union(variants.map(variant => renderType(variant, indent)));
  const types = Array.isArray(schema.type) ? schema.type as string[] : schema.type ? [schema.type as string] : [];
  if (types.length > 1) return union(types.map(type => renderType({ ...schema, type }, indent)));
  switch (types[0]) {
    case 'string': return 'string';
    case 'integer':
    case 'number': return 'number';
    case 'boolean': return 'boolean';
    case 'null': return 'null';
    case 'array': return arrayOf(schema.items ? renderType(schema.items as JsonSchema, indent) : 'unknown');
    case 'object': return objectBody(schema, indent);
    default: return 'unknown';
  }
}

function renderDeclaration(name: string, schema: JsonSchema): string {
  const type = renderType(schema);
  const doc = jsDoc(schema.description, '');
  return type.startsWith('{')
    ? `${doc}export interface ${name} ${type}\n`
    : `${doc}export type ${name} = ${type};\n`;
}

function pascal(value: string): string {
  return value[0].toUpperCase() + value.slice(1);
}

/** Query parameter objects of documented operations, for example `ListTasksQuery`. */
function queryDeclarations(document: OpenApiDocument): string[] {
  const declarations: string[] = [];
  for (const operations of Object.values(document.paths)) {
    for (const operation of Object.values(operations)) {
      if (operation['x-undocumented']) continue;
      const query = ((operation.parameters ?? []) as JsonSchema[]).filter(parameter => parameter.in === 'query');
      if (!query.length) continue;
      const schema: JsonSchema = {
        type: 'object',
        description: `Query parameters of \`${operation.operationId as string}\`.`,
        properties: Object.fromEntries(query.map(parameter => [
          parameter.name, { ...(parameter.schema as JsonSchema), description: parameter.description },
        ])),
        required: query.filter(parameter => parameter.required).map(parameter => parameter.name),
      };
      declarations.push(renderDeclaration(`${pascal(operation.operationId as string)}Query`, schema));
    }
  }
  return declarations.sort();
}

export function renderClientTypes(document: OpenApiDocument): string {
  const components = Object.entries(document.components.schemas)
    .map(([name, schema]) => renderDeclaration(name, schema));
  return `${HEADER}\n${[...components, ...queryDeclarations(document)].join('\n')}`;
}
