// GENERATED CODE! DO NOT MODIFY BY HAND!
// Generated by `codex app-server generate-ts --experimental` (Codex CLI 0.146.0).
export type ThreadGoalStatus =
  | 'active' | 'paused' | 'blocked' | 'usageLimited' | 'budgetLimited' | 'complete';
export type ThreadGoal = {
  threadId: string;
  objective: string;
  status: ThreadGoalStatus;
  tokenBudget: number | null;
  tokensUsed: number;
  timeUsedSeconds: number;
  createdAt: number;
  updatedAt: number;
};
export type ThreadGoalSetParams = {
  threadId: string;
  objective?: string | null;
  status?: ThreadGoalStatus | null;
  tokenBudget?: number | null;
};
export type ThreadGoalSetResponse = { goal: ThreadGoal };
export type ThreadGoalGetParams = { threadId: string };
export type ThreadGoalGetResponse = { goal: ThreadGoal | null };
export type ThreadGoalClearParams = { threadId: string };
export type ThreadGoalClearResponse = { cleared: boolean };
